#!/usr/bin/env bash
set -euo pipefail

# --------------------------------------------------
# Direct Amplify Deployment Script
# Builds locally and deploys directly to Amplify
# Usage: ./deploy-amplify-direct.sh
# --------------------------------------------------

echo "🚀 Starting Direct Amplify Deployment..."
echo "📋 This script will:"
echo "  1. Retrieve backend configuration from CloudFormation"
echo "  2. Build the React app locally"
echo "  3. Deploy directly to Amplify"
echo ""

# --------------------------------------------------
# Retrieve CDK Outputs
# --------------------------------------------------

echo "🔍 Retrieving backend configuration..."

STACK_NAME="CdkBackendStack"

# Function to get CDK output value
get_output() {
  local output_key="$1"
  aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --query "Stacks[0].Outputs[?OutputKey=='$output_key'].OutputValue" \
    --output text \
    --no-cli-pager 2>/dev/null || echo ""
}

# Get all required outputs
echo "Fetching CloudFormation outputs..."
AMPLIFY_APP_ID=$(get_output "AmplifyAppId")
REACT_APP_AMPLIFY_APP_URL=$(get_output "AmplifyAppURL")
REACT_APP_USER_POOL_ID=$(get_output "UserPoolId")
REACT_APP_USER_POOL_CLIENT_ID=$(get_output "UserPoolClientId")
REACT_APP_USER_POOL_DOMAIN=$(get_output "UserPoolDomain")
REACT_APP_IDENTITY_POOL_ID=$(get_output "IdentityPoolId")
REACT_APP_UPDATE_FIRST_SIGN_IN_ENDPOINT=$(get_output "UpdateFirstSignInEndpoint")
REACT_APP_CHECK_UPLOAD_QUOTA_ENDPOINT=$(get_output "CheckUploadQuotaEndpoint")
REACT_APP_JOB_HISTORY_ENDPOINT=$(get_output "JobHistoryEndpoint")
REACT_APP_UPDATE_ATTRIBUTES_API_ENDPOINT=$(get_output "UpdateAttributesApiEndpoint377B5108")

# Get bucket names from stack resources
PDF_TO_PDF_BUCKET=$(aws cloudformation describe-stack-resources \
  --stack-name "$STACK_NAME" \
  --query "StackResources[?ResourceType=='AWS::S3::Bucket' && contains(PhysicalResourceId, 'pdfaccessibility')].PhysicalResourceId" \
  --output text \
  --no-cli-pager 2>/dev/null | head -n1 || echo "")

PDF_TO_HTML_BUCKET=$(aws cloudformation describe-stack-resources \
  --stack-name "$STACK_NAME" \
  --query "StackResources[?ResourceType=='AWS::S3::Bucket' && contains(PhysicalResourceId, 'pdf2html')].PhysicalResourceId" \
  --output text \
  --no-cli-pager 2>/dev/null | head -n1 || echo "")

# Get AWS region
AWS_REGION=$(aws configure get region || echo "us-east-1")

# Validate required outputs
if [ -z "$AMPLIFY_APP_ID" ] || [ "$AMPLIFY_APP_ID" = "None" ]; then
  echo "❌ Error: Could not find AmplifyAppId in stack outputs"
  echo "Make sure the backend stack '$STACK_NAME' is deployed"
  exit 1
fi

echo "✅ Retrieved configuration:"
echo "  - Amplify App ID: $AMPLIFY_APP_ID"
echo "  - Amplify URL: $REACT_APP_AMPLIFY_APP_URL"
echo "  - User Pool ID: $REACT_APP_USER_POOL_ID"
echo "  - User Pool Client ID: $REACT_APP_USER_POOL_CLIENT_ID"
echo "  - Identity Pool ID: $REACT_APP_IDENTITY_POOL_ID"
echo "  - PDF-to-PDF Bucket: ${PDF_TO_PDF_BUCKET:-Not found}"
echo "  - PDF-to-HTML Bucket: ${PDF_TO_HTML_BUCKET:-Not found}"
echo "  - AWS Region: $AWS_REGION"
echo ""

# --------------------------------------------------
# Configure S3 CORS for Browser Uploads
# --------------------------------------------------

echo "🔧 Configuring S3 CORS for browser uploads..."

CORS_CONFIG='{"CORSRules":[{"AllowedHeaders":["*"],"AllowedMethods":["GET","HEAD","PUT","POST","DELETE"],"AllowedOrigins":["*"],"ExposeHeaders":["ETag","x-amz-request-id"]}]}'

if [ -n "${PDF_TO_PDF_BUCKET:-}" ]; then
  aws s3api put-bucket-cors --bucket "$PDF_TO_PDF_BUCKET" --cors-configuration "$CORS_CONFIG" --no-cli-pager 2>/dev/null && \
    echo "  ✅ CORS configured for PDF-to-PDF bucket" || \
    echo "  ⚠️  Failed to set CORS on PDF-to-PDF bucket (may need manual configuration)"
fi

if [ -n "${PDF_TO_HTML_BUCKET:-}" ]; then
  aws s3api put-bucket-cors --bucket "$PDF_TO_HTML_BUCKET" --cors-configuration "$CORS_CONFIG" --no-cli-pager 2>/dev/null && \
    echo "  ✅ CORS configured for PDF-to-HTML bucket" || \
    echo "  ⚠️  Failed to set CORS on PDF-to-HTML bucket (may need manual configuration)"
fi

echo ""

# --------------------------------------------------
# Create .env.production File
# --------------------------------------------------

echo "📝 Creating .env.production file..."

cd pdf_ui

cat > .env.production << EOF
# Auto-generated by deploy-amplify-direct.sh
# Generated: $(date)

# AWS Configuration
REACT_APP_AWS_REGION=$AWS_REGION
REACT_APP_BUCKET_REGION=$AWS_REGION

# Cognito Configuration
REACT_APP_USER_POOL_ID=$REACT_APP_USER_POOL_ID
REACT_APP_USER_POOL_CLIENT_ID=$REACT_APP_USER_POOL_CLIENT_ID
REACT_APP_IDENTITY_POOL_ID=$REACT_APP_IDENTITY_POOL_ID
REACT_APP_USER_POOL_DOMAIN=$REACT_APP_USER_POOL_DOMAIN

# Amplify Configuration
REACT_APP_HOSTED_UI_URL=$REACT_APP_AMPLIFY_APP_URL
REACT_APP_AUTHORITY=$REACT_APP_USER_POOL_DOMAIN

# S3 Buckets
REACT_APP_PDF_BUCKET_NAME=${PDF_TO_PDF_BUCKET:-}
REACT_APP_HTML_BUCKET_NAME=${PDF_TO_HTML_BUCKET:-}

# API Endpoints
REACT_APP_UPDATE_FIRST_SIGN_IN=$REACT_APP_UPDATE_FIRST_SIGN_IN_ENDPOINT
REACT_APP_UPLOAD_QUOTA_API=$REACT_APP_CHECK_UPLOAD_QUOTA_ENDPOINT
REACT_APP_JOB_HISTORY_API=$REACT_APP_JOB_HISTORY_ENDPOINT
REACT_APP_UPDATE_ATTRIBUTES_API=$REACT_APP_UPDATE_ATTRIBUTES_API_ENDPOINT

# Domain Configuration
REACT_APP_DOMAIN_PREFIX=$(echo $REACT_APP_USER_POOL_DOMAIN | cut -d'.' -f1)
EOF

echo "✅ Created .env.production"
echo ""

# --------------------------------------------------
# Install Dependencies
# --------------------------------------------------

echo "📦 Installing dependencies..."
if [ ! -d "node_modules" ]; then
  npm install
else
  echo "✅ Dependencies already installed"
fi
echo ""

# --------------------------------------------------
# Build React App
# --------------------------------------------------

echo "🔨 Building React application..."
npm run build

if [ $? -ne 0 ]; then
  echo "❌ Build failed"
  exit 1
fi

echo "✅ Build completed successfully"
echo ""

# --------------------------------------------------
# Create Deployment Package
# --------------------------------------------------

echo "📦 Creating deployment package..."

cd build
zip -r ../deployment.zip . > /dev/null 2>&1

if [ $? -ne 0 ]; then
  echo "❌ Failed to create deployment package"
  exit 1
fi

cd ..
echo "✅ Created deployment.zip"
echo ""

# --------------------------------------------------
# Deploy to Amplify
# --------------------------------------------------

echo "🚀 Deploying to Amplify..."

# Create deployment
echo "Creating Amplify deployment..."
DEPLOYMENT_RESPONSE=$(aws amplify create-deployment \
  --app-id "$AMPLIFY_APP_ID" \
  --branch-name main \
  --output json \
  --no-cli-pager)

if [ $? -ne 0 ]; then
  echo "❌ Failed to create Amplify deployment"
  exit 1
fi

# Extract upload URL and job ID
UPLOAD_URL=$(echo "$DEPLOYMENT_RESPONSE" | jq -r '.zipUploadUrl')
JOB_ID=$(echo "$DEPLOYMENT_RESPONSE" | jq -r '.jobId')

echo "✅ Deployment created (Job ID: $JOB_ID)"

# Upload the deployment package
echo "Uploading build artifacts..."
curl -X PUT \
  -H "Content-Type: application/zip" \
  --data-binary @deployment.zip \
  "$UPLOAD_URL" \
  --silent \
  --show-error

if [ $? -ne 0 ]; then
  echo "❌ Failed to upload deployment package"
  exit 1
fi

echo "✅ Upload completed"

# Start the deployment
echo "Starting Amplify deployment..."
aws amplify start-deployment \
  --app-id "$AMPLIFY_APP_ID" \
  --branch-name main \
  --job-id "$JOB_ID" \
  --source-url "$UPLOAD_URL" \
  --no-cli-pager > /dev/null

if [ $? -ne 0 ]; then
  echo "❌ Failed to start deployment"
  exit 1
fi

echo "✅ Deployment started"
echo ""

# --------------------------------------------------
# Monitor Deployment Status
# --------------------------------------------------

echo "⏳ Monitoring deployment status..."
echo "This may take a few minutes..."
echo ""

DEPLOYMENT_STATUS="PENDING"
RETRY_COUNT=0
MAX_RETRIES=60  # 5 minutes with 5-second intervals

while [ "$DEPLOYMENT_STATUS" != "SUCCEED" ] && [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
  sleep 5
  
  DEPLOYMENT_STATUS=$(aws amplify get-job \
    --app-id "$AMPLIFY_APP_ID" \
    --branch-name main \
    --job-id "$JOB_ID" \
    --query 'job.summary.status' \
    --output text \
    --no-cli-pager 2>/dev/null || echo "PENDING")
  
  case "$DEPLOYMENT_STATUS" in
    "SUCCEED")
      echo "✅ Deployment succeeded!"
      break
      ;;
    "FAILED"|"CANCELLED")
      echo "❌ Deployment $DEPLOYMENT_STATUS"
      echo "Check Amplify console for details: https://console.aws.amazon.com/amplify/home?region=$AWS_REGION#/$AMPLIFY_APP_ID"
      exit 1
      ;;
    *)
      echo "Status: $DEPLOYMENT_STATUS ($(($RETRY_COUNT * 5))s elapsed)"
      ;;
  esac
  
  RETRY_COUNT=$((RETRY_COUNT + 1))
done

if [ $RETRY_COUNT -ge $MAX_RETRIES ]; then
  echo "⚠️  Deployment is taking longer than expected"
  echo "Check status in Amplify console: https://console.aws.amazon.com/amplify/home?region=$AWS_REGION#/$AMPLIFY_APP_ID"
fi

# --------------------------------------------------
# Cleanup
# --------------------------------------------------

echo ""
echo "🧹 Cleaning up..."
rm -f deployment.zip
echo "✅ Cleanup completed"

# --------------------------------------------------
# Final Summary
# --------------------------------------------------

echo ""
echo "🎉 Deployment Complete!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 Summary:"
echo "  - Amplify App ID: $AMPLIFY_APP_ID"
echo "  - Deployment URL: $REACT_APP_AMPLIFY_APP_URL"
echo "  - Job ID: $JOB_ID"
echo "  - Branch: main"
echo "  - Status: $DEPLOYMENT_STATUS"
echo ""
echo "🌐 Your application should be live at:"
echo "   $REACT_APP_AMPLIFY_APP_URL"
echo ""
echo "📱 View deployment details:"
echo "   https://console.aws.amazon.com/amplify/home?region=$AWS_REGION#/$AMPLIFY_APP_ID"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

cd ..
exit 0
